# dnscrypt-proxy configuration

# Global settings
#===============================================================================

listen_addresses = ['127.0.0.53:53']
ipv4_servers = true
ipv6_servers = false
block_ipv6 = true

server_names = ['cloudflare']
fallback_resolver = '1.1.1.1:53'
ignore_system_dns = true

max_clients = 1024
timeout = 2500

cert_refresh_delay = 240
dnscrypt_servers = true
doh_servers = true
force_tcp = false
require_dnssec = true
require_nofilter = true
require_nolog = true

log_file = '/var/log/dnscrypt-proxy/dnscrypt-proxy.log'
log_level = 2
log_files_max_size = 10
log_files_max_age = 7
log_files_max_backups = 1

# Route queries for specific domains to a dedicated set of servers
#===============================================================================

# forwarding_rules = 'forwarding-rules.txt'

# Cloaking rules
#===============================================================================

# cloaking_rules = 'cloaking-rules.txt'

# DNS cache
#===============================================================================

cache = true
cache_size = 384
cache_min_ttl = 600
cache_max_ttl = 86400
cache_neg_ttl = 60

# Query logging
#===============================================================================

[query_log]
  file = '/var/log/dnscrypt-proxy/query.log'
  format = 'tsv'
  ignored_qtypes = ['NS']

# Suspicious queries logging
#===============================================================================

[nx_log]
  file = '/var/log/dnscrypt-proxy/nx.log'
  format = 'tsv'

# Pattern-based blocking (blacklists)
#===============================================================================

[blacklist]
  # blacklist_file = "/opt/dnscrypt.blocklist"
  log_file = '/var/log/dnscrypt-proxy/blocked.log'
  log_format = 'tsv'

# Pattern-based IP blocking (IP blacklists)
#===============================================================================

[ip_blacklist]
  # blacklist_file = 'ip-blacklist.txt'
  log_file = '/var/log/dnscrypt-proxy/ip-blocked.log'
  log_format = 'tsv'

# Time access restrictions
#===============================================================================

[schedules]
  # [schedules.'time-to-sleep']
  # mon = [{after='21:00', before='7:00'}]
  # tue = [{after='21:00', before='7:00'}]
  # wed = [{after='21:00', before='7:00'}]
  # thu = [{after='21:00', before='7:00'}]
  # fri = [{after='23:00', before='7:00'}]
  # sat = [{after='23:00', before='7:00'}]
  # sun = [{after='21:00', before='7:00'}]

# Servers
#===============================================================================

[sources]
  [sources.'public-resolvers']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md']
  cache_file = 'public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''

[static]
  # [static.'google']
  # stamp = 'sdns://AgUAAAAAAAAAACDyXGrcc5eNecJ8nomJCJ-q6eCLTEn6bHic0hWGUwYQaA5kbnMuZ29vZ2xlLmNvbQ0vZXhwZXJpbWVudGFs'
