# dnscrypt-proxy.toml

################################################################################
# Global settings
################################################################################

listen_addresses = ['127.0.0.53:53']
ipv4_servers = true
ipv6_servers = false
block_ipv6 = true

server_names = ['cloudflare-security']
fallback_resolver = '1.1.1.2:53'
ignore_system_dns = true

max_clients = 100
timeout = 3000

cert_refresh_delay = 60
dnscrypt_servers = true
doh_servers = true
force_tcp = false
require_dnssec = true
require_nofilter = true
require_nolog = true

log_file = '/var/log/dnscrypt-proxy/dnscrypt-proxy.log'
log_level = 2
log_files_max_size = 10
log_files_max_age = 7
log_files_max_backups = 1

################################################################################
# DNS Caching
################################################################################

cache = true
cache_size = 8196
cache_min_ttl = 900
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600

################################################################################
# DNS Sources
################################################################################

[sources]
  [sources.'public-resolvers']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md']
  cache_file = 'public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''

[static]
  [static.'NextDNS-ea1a22']
  stamp = 'sdns://AgEAAAAAAAAACjQ1LjkwLjI4LjAADmRucy5uZXh0ZG5zLmlvBy9lYTFhMjI'

################################################################################
# Blocklist
################################################################################

[blacklist]
  # blacklist_file = "/opt/dnscrypt.blocklist"
  log_file = '/var/log/dnscrypt-proxy/blocked.log'
  log_format = 'tsv'

[ip_blacklist]
  # blacklist_file = 'ip-blacklist.txt'
  log_file = '/var/log/dnscrypt-proxy/ip-blocked.log'
  log_format = 'tsv'

################################################################################
# Logging
################################################################################

[query_log]
  file = '/var/log/dnscrypt-proxy/query.log'
  format = 'tsv'
  ignored_qtypes = ['NS']

[nx_log]
  file = '/var/log/dnscrypt-proxy/nx.log'
  format = 'tsv'
